# 👇 This is your plugin manifest. It tells Make It So how to run your plugin.
[plugin]
name = "sample-plugin"
version = "0.1.0"
description = "A plugin scaffolded by Make It So."

# 👇 These are the CLI commands this plugin supports
[commands.moo]
description = "Moo!!!!"
script = "./moo.ts"

# 👇 These are any external dependencies your plugin needs
[deno_dependencies]
# You can import any Deno-compatible module here by name
# Example: using `cowsay` to print a message
cowsay = "https://deno.land/x/cowsay@1.1/mod.ts"

# 👇 Everything below here is YOUR plugin-specific config that you can access in .ts via the ctx variable.
[user_config]
# Message to print out — this config is passed into your plugin via ctx.config
message = "Make It So 🪄"
